emotool: start serial2tcp in subprocess
kill on complete (not killing all existing users of the com port on
start - TODO)

Getting exception from proactor event loop on close because of premature
closing of the event loop - need to cleanup - what exactly? the process?
the read socket?

Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorSocketTransport closing fd=644 read=<_OverlappedFuture finished result=b'\xed0@A\xff...x00EM\x08\x1c'>>>
Traceback (most recent call last):
  File "C:\Python35\lib\asyncio\proactor_events.py", line 90, in __del__
  File "C:\Python35\lib\asyncio\proactor_events.py", line 78, in close
  File "C:\Python35\lib\asyncio\base_events.py", line 497, in call_soon
  File "C:\Python35\lib\asyncio\base_events.py", line 506, in_call_soon
  File "C:\Python35\lib\asyncio\base_events.py", line 334, in _check_closed
  RuntimeError: Event loop is closed